# Generated by Django 6.0.1 on 2026-01-19 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(db_index=True, max_length=32, unique=True),
        ),
    ]
