# Generated by Django 6.0.1 on 2026-01-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_alter_usermodel_password_alter_usermodel_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True)),
            ],
            options={
                'db_table': 'regionals',
            },
        ),
    ]
