# Generated by Django 6.0.1 on 2026-01-22 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_regionalmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('plate_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('color', models.CharField(max_length=30)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='infrastructure.regionalmodel')),
            ],
            options={
                'db_table': 'cars',
                'indexes': [models.Index(fields=['regional', 'created_at'], name='cars_regiona_482316_idx')],
            },
        ),
    ]
