openapi: 3.0.3

info:
  title: MeRental API
  description: Base API contract for MeRental backend services.
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /ping:
    get:
      summary: Ping the server
      operationId: ping
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
  /auth/register:
    post:
      summary: Register a new user
      description: Register a new user account and return a confirmation message upon successful registration.
      operationId: registerUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
                - confirmPassword
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 32
                  pattern: "^[a-zA-Z0-9_]+$"
                  example: mieintel
                password:
                  type: string
                  format: password
                  minLength: 8
                  maxLength: 128
                  description: >
                    Password must be between 8 and 128 characters long and contain at least one uppercase
                    letter, one lowercase letter, one digit, and one special character.
                  example: your_secure_password
                confirmPassword:
                  type: string
                  format: password
                  minLength: 8
                  maxLength: 128
                  description: >
                    Must match the password field and follow the same password requirements
                    (at least one uppercase letter, one lowercase letter, one digit, and one special character).
                  example: your_secure_password
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: User registered successfully
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: Validation error
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: Username already exists
  /auth/login:
    post:
      summary: Authenticate user and generate access token
      description: Authenticates a user with a username and password and returns an access token on successful login.
      operationId: loginUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 32
                  pattern: "^[a-zA-Z0-9_]+$"
                  example: mieintel
                password:
                  type: string
                  format: password
                  minLength: 8
                  maxLength: 128
                  example: your_secure_password
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - token
                properties:
                  message:
                    type: string
                    example: User logged in successfully
                  token:
                    type: string
                    description: >
                      JSON Web Token (JWT) access token used for authenticated requests.
                      Include this value in the "Authorization" header using the Bearer scheme,
                      for example: "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...".
                      The token is time-limited (for example, typically valid for about 15 minutes)
                      and must be refreshed or reissued after it expires.
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: Missing required fields or invalid request format
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
                    example: Invalid credentials

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    ErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    BadRequestErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: Validation error
    ConflictErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: Username already exists
    UnauthorizedErrorResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          example: Invalid credentials
