openapi: 3.0.3

info:
  title: MeRental API
  description: Base API contract for MeRental backend services.
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Local development server