openapi: 3.0.3

info:
  title: MeRental API
  description: Base API contract for MeRental backend services.
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /ping:
    get:
      summary: Ping the server
      operationId: ping
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
